### ISSUE TITLE
return geometry key in aggregated.to_dataframe()

### ISSUE THREAD

**Issue by raybellwaves** [ks905383/xagg#17]
When doing `aggregated.to_dataframe()` it drops the geometry column that is in the original `geopandas.DataFrame`.

It would be nice if it was returned to be used for things such as visualization.

<img width="723" alt="Screen Shot 2021-08-26 at 10 44 18 PM" src="https://user-images.githubusercontent.com/17162724/131063721-d9bf22a4-b40a-4918-a352-797a67ffdf2f.png">

<img width="552" alt="Screen Shot 2021-08-26 at 10 44 34 PM" src="https://user-images.githubusercontent.com/17162724/131063757-0c679d4c-f6a1-45e4-91ad-a18ad2328545.png">

<img width="1358" alt="Screen Shot 2021-08-26 at 10 50 34 PM" src="https://user-images.githubusercontent.com/17162724/131064296-c145415a-5ea2-4efd-9255-ff17d4217f56.png">

Code:

```
import geopandas as gpd
import pooch
import xagg as xa
import xarray as xr
import hvplot.pandas

# Load in example data and shapefiles
ds = xr.tutorial.open_dataset("air_temperature").isel(time=0)
file = pooch.retrieve(
    "https://pubs.usgs.gov/of/2006/1187/basemaps/continents/continents.zip", None
)
continents = gpd.read_file("zip://" + file)
continents

wm = xa.pixel_overlaps(ds, continents)
aggregated = xa.aggregate(ds, wm)
aggregated.to_dataframe()

pd.merge(aggregated.to_dataframe(), continents, on="CONTINENT").hvplot(c="air")
```

**Comment by ks905383** [comment]
Added by #25
