### ISSUE TITLE
add link to docs in sidebar

### ISSUE THREAD

**Issue by raybellwaves** [ks905383/xagg#18]
There's some one in the github repo configuration you can add docs to the right side bar

<img width="1037" alt="Screen Shot 2021-08-26 at 10 59 56 PM" src="https://user-images.githubusercontent.com/17162724/131065154-2ec28f15-0a2e-4d59-be43-54c5b8af31eb.png">

e.g. https://github.com/xarray-contrib/xskillscore in the About section on the right

**Comment by ks905383** [comment]
Done!
