### ISSUE TITLE
silence functions

### ISSUE THREAD

**Issue by khalilT** [ks905383/xagg#38]
Hi, thank you a lot for the great package.

I was wondering if it is possible to add an argument to the functions (pixel_overlaps and aggregate) to silence them if we want? I am doing aggregations for many geometries and sometimes it becomes too crowded, especially if I try to print other things along while the functions are executed.

Thanks !

**Comment by ks905383** [comment]
That should be possible! (Sorry for the late response) - I'll see if I can add it in the next release.

**Comment by ks905383** [comment]
Closed by #42 , upcoming in v0.3.1

**Comment by ks905383** [comment]
...I missed the ones in `xagg.aux`, e.g. `lat/lon bounds not found in dataset; they will be created.` in `xagg.aux.get_bnds()`. Will fix for the next version...
