### ISSUE TITLE
silent=True not suppressing messages

### ISSUE THREAD

**Issue by helsharif** [ks905383/xagg#55]
Hello,
In using pixel_overlaps and aggregate functions I include silent=True, but I still get the same messages printed to the screen whether I include that or not. I was expecting for there to be no output to screen.

**Comment by helsharif** [comment]
Hello,
Below I'm adding a screenshot of the warning messages I get when running pixel_overlaps and aggregate even with silent=True

![image](https://github.com/ks905383/xagg/assets/14345478/5f1a3519-6207-4542-bbe2-0e0f7e69ff06)

**Comment by ks905383** [comment]
Yeah fair - 

Looks like there are a few causes of that 
1. Use of `.dims` instead of `.sizes` (easy enough to fix)
2. Not suppressing the `print()` calls 
3. That one `xagg` warning as well.

I'll see if I can fix that in the next version. 

In the interim, 
```
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings('ignore')
    [xagg code here]
```
Should get rid of at least the warnings.

**Comment by ks905383** [comment]
https://github.com/ks905383/xagg/pull/63#issuecomment-1954112998

One subfunction still doesn't have `silent` piped into it. This is through this line https://github.com/ks905383/xagg/blob/db8df95664c2ccceae4ad1f7dd5fb711af07bc38/xagg/core.py#L616, which should have `silent=silent` show up in the `subset_find()` call. 

@helsharif can you confirm this is the only place where `silent=True` is still not producing the desired results?

**Comment by helsharif** [comment]
Hi, yes I confirm. It seems like the other warning messages have gone away with the latest version. The only messages I still see are:
"adjusting grid... (this may happen because only a subset of pixels were used for aggregation for efficiency - i.e. [subset_bbox=True] in xa.pixel_overlaps())"
and
"grid adjustment successful"

**Comment by ks905383** [comment]
@helsharif sorry for the delay - I think it should now be fixed in v0.3.2.1. You can also now set silent=True as a global option with 

`xa.set_options(silent=True)`. 

Let me know if it doesn't work!

**Comment by helsharif** [comment]
Thanks! Yes it is working and the extra messages are suppressed. I just started a new project that involves a lot of use of xagg today, so this is a big help! Best regards. I think it is safe to close this thread.

**Comment by helsharif** [comment]
thanks!
