### ISSUE TITLE
Dimensions Issue

### ISSUE THREAD

**Issue by loganbundy** [ks905383/xagg#56]
I have run into an issue with the dimensions I believe. I receive the error message: 

ValueError: new dimensions ('lat', 'bnds') must be a superset of existing dimensions ('lat', 'bnd') 

when trying to run the xa.pixel_overlaps function. 

I have tried numerous datasets to see if the issue persists, and it does. I see this issue has been raised before, but I am unsure how to solve it...

**Comment by ks905383** [comment]
Hi @loganbundy , I think that was raised in  #50  - should be fixed with the newest version (0.3.1.1). Let me know if that doesn't work!
