### ISSUE TITLE
Warning in `xa.aggregate()` 

### ISSUE THREAD

**Issue by ks905383** [ks905383/xagg#57]
During the `aggregated = xa.aggregate(ds_tas, weightmap)` step, I am getting the following repeated warning: 

`RuntimeWarning: invalid value encountered in divide
  a2 = a2/a2.sum()`

_Originally posted by @kls2177 in https://github.com/atrisovic/weather-panel.github.io/issues/79#issuecomment-1917866333_

**Comment by ks905383** [comment]
This is in `xa.aux.normalize()`; probably because a fully empty (or entirely 0) time series is provided? 

Todo: 
[ ] Check whether this is due to something else breaking 
[ ] Possibly suppress using something like: `if not np.all(np.isnan(a)):`

**Comment by kls2177** [comment]
@ks905383 The population data has a lot of zeros and the temperature data has masked values over ocean.

Also, note that when I plot the map of summer temperature, there are a few spots over the US that are also missing data (figure attached)
<img width="975" alt="tas_JJA_BEST_map" src="https://github.com/ks905383/xagg/assets/13908222/aa68d365-ae65-433a-8776-28e555fe3b3d">
.

**Comment by ks905383** [comment]
@kls2177 thanks for that clarification!

Could you move the issue with the map over to the JOSE review? This repo is for `xagg`, the code package used in one of the examples.

**Comment by ks905383** [comment]
Turns out this only shows up when additional `weights` are used. It's possible for all `weights` pixels for a given polygon to = 0 in a location; in this case `normalize` throws a divide by 0 warning, because the sum of the weights to be normalize = 0. The workaround is for normalize to just return the input vector if all the inputs are 0 or nan.

**Comment by ks905383** [comment]
Fixed and implemented in [v0.3.2.0](https://github.com/ks905383/xagg/releases/tag/v0.3.2.0)
