### ISSUE TITLE
InvalidArchiveError aux.py not found (Windows 10, miniconda)

### ISSUE THREAD

**Issue by dmrwal** [ks905383/xagg#58]
Hi, I came across your package and would like to try it out. But I run into an issue whenever I try to install it with miniconda into my python environment. 

`InvalidArchiveError("Error with archive C:\\Users\\user\\miniconda3\\pkgs\\xagg-0.3.1.1-pyhd8ed1ab_0.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 2] No such file or directory: 'C:\\\\Users\\\\user\\\\miniconda3\\\\pkgs\\\\xagg-0.3.1.1-pyhd8ed1ab_0\\\\site-packages\\\\xagg\\\\aux.py'")`

I've tried cleaning up conda with `conda clean --all`, which seems to be a common approach to the InvalidArchiveError. However, the aux.py file for the installation seems to be missing. Did this issue ever come up before and is there a solution for this? 

Background: I'm running this in miniconda on Windows 10 Pro

Thanks a lot in advance for any help or advice on this!

**Comment by ks905383** [comment]
Hi @dmrwal ,

So I think it's because `aux` may be a reserved filename in windows... (it's come up before in #23 ) I don't have a windows machine, so I'm not able to test this (/ don't really know how conda works in windows) - but would you be able to locally test to see if renaming `aux.py` to anything else makes that problem go away?

**Comment by dmrwal** [comment]
Thanks for the quick response @ks905383,

totally understand. I tried to find an option to rename the file, but unsure if this is possible during the installation from the conda-forge. At least for me the ´xagg-0.3.1.1-...´ CONDA file is not accessible with common readers.

Could it be an option to install the package from the repo directly?

**Comment by dmrwal** [comment]
Quick update: I also tried to clone the repo via 
`pip install git+git://github.com/ks905383/xagg`

But this does not seem to be possible (results in multiple other errors. 
Any further advice, or tips for installation on a windows 10 machine are highly appreciated.

Thanks again!

**Comment by ks905383** [comment]
Yeah... some of the dependencies are no longer on pip, so you can only install an old version through pip... 

I'm trying to get an update out with some bug fixes in the near future; I'll change the name of the `aux.py` submodule and hopefully that will fix it. I'll let you know when that's out!

**Comment by ks905383** [comment]
Should be closed by #61 and implemented in the latest version v0.3.2.0 https://github.com/ks905383/xagg/releases/tag/v0.3.2.0

**Comment by dmrwal** [comment]
Thanks for this!
We eventually succeeded with the installation by forking, downloading, changing the file name and manually installing with pip. Works for now without issues on Win 10 Pro.
Will check for another installation from the new release.
