### ISSUE TITLE
Citation Files

### ISSUE THREAD

**Issue by JPMastrogiacomo** [ks905383/xagg#82]
Have you considered adding citation files? I will be citing this repository and it might make things nicer

[https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)

**Comment by ks905383** [comment]
Ah great idea. There's a write-up currently [under review](https://github.com/openjournals/joss-reviews/issues/7239) at JOSS that should eventually probably be the thing that's cited, but in the meantime I do have a DOI for this now, so it would be a good idea to direct people to that. Thanks for suggesting!
